services:
  svn:
    build:
      context: .
      dockerfile: Containerfile
    ports:
      - 3690:3690
    volumes:
      - ./svn_data:/home/svn
      - ./svn_config:/etc/subversion
    environment:
      # From .env (auto-loaded by docker compose)
      # Optional: override home directory inside container
      - HOME_DIR=${HOME_DIR}
    healthcheck:
      test: ["CMD", "/usr/local/bin/healthcheck.sh"]
      interval: 30s
      timeout: 5s
      retries: 3
