services:
  svn:
    build:
      context: .
      dockerfile: Containerfile
    ports:
      - 3690:3690
    volumes:
      - ./data:/home/svn
    environment:
      - SVN_REPO_NAME=my_repo
      - SVN_REPO_PATH=/home/svn/${SVN_REPO_NAME}
      - SVN_REPO_URL=file://${SVN_REPO_PATH}